Repository entando-k8s/entando-k8s-keycloak-controller, pull requests merged in 2020-08, with the labels that each got.

#7 bumped operator-common to 6.1.13
  pom.xml
  src/test/java/org/entando/kubernetes/controller/keycloakserver/inprocesstests/DeployKeycloakServiceTest.java
Labels: approved, size/XS

#8 Eng 1020 migrate to keycloak 11
  pom.xml
  src/main/java/org/entando/kubernetes/controller/keycloakserver/EntandoKeycloakServerController.java
  src/main/resources/realm-base.json
  src/test/java/org/entando/kubernetes/controller/keycloakserver/inprocesstests/DeployKeycloakServiceTest.java
  src/test/java/org/entando/kubernetes/controller/keycloakserver/interprocesstests/AddEntandoKeycloakServerWithContainerizedDatabaseIT.java
Labels: size/XXL

#9 Eng 1065 configurable serviceaccounts
  pom.xml
Labels: approved, size/XS

#10 ENG-1065 rewriting connection-secret to local namespace now
  src/main/java/org/entando/kubernetes/controller/keycloakserver/EntandoKeycloakServerController.java
Labels: approved, size/M
